name: Deploy Python project to Azure Function App

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch.

env:
  AZURE_FUNCTIONAPP_NAME: 'fypratinascan'   # Replace with your Azure Function App name.
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'                # Assuming FastAPI app is in the root directory.
  PYTHON_VERSION: '3.1'                              # Python version to use (e.g., '3.9').

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Runs on an Ubuntu machine.
    environment: dev        # Optional: Set up a deployment environment (optional).

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v4  # Checks out the code from your repository.

    - name: 'Set up Python ${{ env.PYTHON_VERSION }}'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}  # Sets up the specified Python version.

    - name: 'Install Dependencies'
      run: |
        pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        python -m pip install --upgrade pip
        pip install -r packages.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Deploy to Azure Function App'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}  # Your Azure Function App name.
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}  # Path to your FastAPI app.
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  # The Publish Profile secret.
        scm-do-build-during-deployment: true  # Build during deployment.
        enable-oryx-build: true  # Optional: Use Oryx build for Azure.

